/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_join_jni_JniTest */

#ifndef _Included_org_join_jni_JniTest
#define _Included_org_join_jni_JniTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_join_jni_JniTest
 * Method:    sayHelloWin
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_org_join_jni_JniTest_sayHelloWin
  (JNIEnv *, jclass, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
